<?php

/**
 * BaseContacto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $nombre
 * @property varchar $primer_apellido
 * @property varchar $segundo_apellido
 * @property varchar $imagen
 * @property integer $visitas
 * @property Doctrine_Collection $Direcciones
 * 
 * @method varchar             getNombre()           Returns the current record's "nombre" value
 * @method varchar             getPrimerApellido()   Returns the current record's "primer_apellido" value
 * @method varchar             getSegundoApellido()  Returns the current record's "segundo_apellido" value
 * @method varchar             getImagen()           Returns the current record's "imagen" value
 * @method integer             getVisitas()          Returns the current record's "visitas" value
 * @method Doctrine_Collection getDirecciones()      Returns the current record's "Direcciones" collection
 * @method Contacto            setNombre()           Sets the current record's "nombre" value
 * @method Contacto            setPrimerApellido()   Sets the current record's "primer_apellido" value
 * @method Contacto            setSegundoApellido()  Sets the current record's "segundo_apellido" value
 * @method Contacto            setImagen()           Sets the current record's "imagen" value
 * @method Contacto            setVisitas()          Sets the current record's "visitas" value
 * @method Contacto            setDirecciones()      Sets the current record's "Direcciones" collection
 * 
 * @package    agenda.symfony
 * @subpackage model
 * @author     Luis Trapero
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContacto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contacto');
        $this->hasColumn('nombre', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('primer_apellido', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('segundo_apellido', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('imagen', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'default' => 'noimg.jpg',
             'length' => 255,
             ));
        $this->hasColumn('visitas', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Direccion as Direcciones', array(
             'local' => 'id',
             'foreign' => 'contacto_id'));
    }
}