<?php

/**
 * BaseDireccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $direccion
 * @property varchar $email
 * @property varchar $telefono
 * @property clob $info_adicional
 * @property boolean $predeterminado
 * @property integer $contacto_id
 * @property Contacto $Contacto
 * 
 * @method clob      getDireccion()      Returns the current record's "direccion" value
 * @method varchar   getEmail()          Returns the current record's "email" value
 * @method varchar   getTelefono()       Returns the current record's "telefono" value
 * @method clob      getInfoAdicional()  Returns the current record's "info_adicional" value
 * @method boolean   getPredeterminado() Returns the current record's "predeterminado" value
 * @method integer   getContactoId()     Returns the current record's "contacto_id" value
 * @method Contacto  getContacto()       Returns the current record's "Contacto" value
 * @method Direccion setDireccion()      Sets the current record's "direccion" value
 * @method Direccion setEmail()          Sets the current record's "email" value
 * @method Direccion setTelefono()       Sets the current record's "telefono" value
 * @method Direccion setInfoAdicional()  Sets the current record's "info_adicional" value
 * @method Direccion setPredeterminado() Sets the current record's "predeterminado" value
 * @method Direccion setContactoId()     Sets the current record's "contacto_id" value
 * @method Direccion setContacto()       Sets the current record's "Contacto" value
 * 
 * @package    agenda.symfony
 * @subpackage model
 * @author     Luis Trapero
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDireccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('direccion');
        $this->hasColumn('direccion', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('email', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('telefono', 'varchar', 9, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 9,
             ));
        $this->hasColumn('info_adicional', 'clob', null, array(
             'type' => 'clob',
             'notnull' => false,
             ));
        $this->hasColumn('predeterminado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('contacto_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Contacto', array(
             'local' => 'contacto_id',
             'foreign' => 'id'));
    }
}