<?php

/**
 * Contacto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    agenda.symfony
 * @subpackage model
 * @author     Luis Trapero
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contacto extends BaseContacto
{
    public function getNombreCompleto()
    {
        return $this->getNombre() . " " . $this->getPrimer_apellido() . " " . $this->getSegundo_apellido();
    }
    
    
    public function getDireccionPredeterminada()
    {
        return Doctrine::getTable('Direccion')->findPredeterminadaDireccionById( $this->getId() );
    }
    
    
    public function deleteDirecciones()
    {
        return Doctrine::getTable('Direccion')->deleteDireccionesById( $this->getId() );
    }
    
    
    public function incrementaVisita()
    {
        $this->setVisitas( $this->getVisitas() + 1 );
        $this->save();
    }
    
    
}