# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        Agenda de contactos en Symfony
    #description:  Agenda de contactos en Symfony Curso Flai
    #keywords:     symfony, project, agenda, contactos
    #language:     es
    #robots:       index, follow

  stylesheets:    [main.css, style.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
